const express = require("express");
const cors = require("cors");

const router = express.Router()

// RUTA GET PARA TRAER PRODUCTOS DE LA DB

// RUTA GET PARA TRAER LOS PRODUCTOS QUE ESTAN EN EL CARRITO

// RUTA POST PARA AGREGAR PRODUCTOS AL CARRITO

// RUTA PUT PARA DISMINUIR O MODIFICAR LA CANTIDAD DE PRODUCTOS DEL CARRITO

// RUTA DELETE PARA ELIMINAR PRODUCTOS DEL CARRITO